// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: xoGoYnzcgCWsQgugY2n8Ua
// Component: wxPX1t5v8jMyKZ
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css"; // plasmic-import: xoGoYnzcgCWsQgugY2n8Ua/projectcss
import * as sty from "./PlasmicRatings.module.css"; // plasmic-import: wxPX1t5v8jMyKZ/css

import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: ICbIjAh5Sp-Uxd/icon

export type PlasmicRatings__VariantMembers = {
  stars: "zero" | "one" | "two" | "three" | "four" | "five";
};

export type PlasmicRatings__VariantsArgs = {
  stars?: SingleChoiceArg<"zero" | "one" | "two" | "three" | "four" | "five">;
};

type VariantPropType = keyof PlasmicRatings__VariantsArgs;
export const PlasmicRatings__VariantProps = new Array<VariantPropType>("stars");

export type PlasmicRatings__ArgsType = {
  numReviews?: React.ReactNode;
};

type ArgPropType = keyof PlasmicRatings__ArgsType;
export const PlasmicRatings__ArgProps = new Array<ArgPropType>("numReviews");

export type PlasmicRatings__OverridesType = {
  root?: p.Flex<"div">;
  box?: p.Flex<"div">;
};

export interface DefaultRatingsProps {
  numReviews?: React.ReactNode;
  stars?: SingleChoiceArg<"zero" | "one" | "two" | "three" | "four" | "five">;
  className?: string;
}

function PlasmicRatings__RenderFunc(props: {
  variants: PlasmicRatings__VariantsArgs;
  args: PlasmicRatings__ArgsType;
  overrides: PlasmicRatings__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__stars_five]: hasVariant(variants, "stars", "five"),
        [sty.root__stars_four]: hasVariant(variants, "stars", "four"),
        [sty.root__stars_one]: hasVariant(variants, "stars", "one"),
        [sty.root__stars_three]: hasVariant(variants, "stars", "three"),
        [sty.root__stars_two]: hasVariant(variants, "stars", "two"),
        [sty.root__stars_zero]: hasVariant(variants, "stars", "zero")
      })}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box)}
      >
        {(hasVariant(variants, "stars", "zero") ? false : true) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__uK132, {
              [sty.svg__stars_five__uK132EknEn]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_zero__uK1329XtAt]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__hqn3Z, {
              [sty.svg__stars_five__hqn3ZEknEn]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__hqn3ZP0Jiy]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__hqn3ZyWxVi]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__hqn3Z2RgUu]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__hqn3ZemsDz]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__hqn3Z9XtAt]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__bjJJh, {
              [sty.svg__stars_five__bjJJhEknEn]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__bjJJhP0Jiy]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__bjJJhyWxVi]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__bjJJh2RgUu]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__bjJJhemsDz]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__bjJJh9XtAt]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__ufWe, {
              [sty.svg__stars_five__ufWeEknEn]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__ufWeP0Jiy]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__ufWeyWxVi]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__ufWe2RgUu]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__ufWeemsDz]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__ufWe9XtAt]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__aLpz, {
              [sty.svg__stars_five__aLpzEknEn]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__aLpzP0Jiy]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__aLpzYWxVi]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__aLpz2RgUu]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__aLpzEmsDz]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__aLpz9XtAt]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? true
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__jYsvq, {
              [sty.svg__stars_five__jYsvqEknEn]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__jYsvqp0Jiy]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__jYsvQyWxVi]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__jYsvq2RgUu]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__jYsvQemsDz]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__jYsvq9XtAt]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__rvUt5, {
              [sty.svg__stars_five__rvUt5EknEn]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__rvUt5P0Jiy]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_three__rvUt52RgUu]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__rvUt5EmsDz]: hasVariant(
                variants,
                "stars",
                "two"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg___7Og4T, {
              [sty.svg__stars_five___7Og4TEknEn]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four___7Og4Tp0Jiy]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_three___7Og4T2RgUu]: hasVariant(
                variants,
                "stars",
                "three"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__ffwxl, {
              [sty.svg__stars_five__ffwxlEknEn]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__ffwxlP0Jiy]: hasVariant(
                variants,
                "stars",
                "four"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(hasVariant(variants, "stars", "five") ? false : true) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__ac472, {
              [sty.svg__stars_five__ac472EknEn]: hasVariant(
                variants,
                "stars",
                "five"
              )
            })}
            role={"img"}
          />
        ) : null}
      </p.Stack>

      <p.PlasmicSlot
        defaultContents={"(45 Review)"}
        value={args.numReviews}
        className={classNames(sty.slotNumReviews)}
      />
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "box"],
  box: ["box"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  box: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRatings__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicRatings__VariantsArgs;
  args?: PlasmicRatings__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicRatings__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicRatings__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRatings__ArgProps,
      internalVariantPropNames: PlasmicRatings__VariantProps
    });

    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings";
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`;
  }
  return func;
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),

    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps
  }
);

export default PlasmicRatings;
/* prettier-ignore-end */
